export enum AttackProcessActionTypes {
  START_ATTACK_PENDING = "START_ATTACK_PENDING",
  START_ATTACK_SUCCESS = "START_ATTACK_SUCCESS",
  START_ATTACK_FAILED = "START_ATTACK_FAILED",
  START_SCANNING_PENDING = "START_SCANNING_PENDING",
  START_SCANNING_SUCCESS = "START_SCANNING_SUCCESS",
  START_SCANNING_FAILED = "START_SCANNING_FAILED",
}
