export enum AttackProcessActionTypes {
  TOOGLE_ASK_SCAN = "TOOGLE_ASK_SCAN",
  START_ATTACK_PENDING = "START_ATTACK_PENDING",
  START_ATTACK_SUCCESS = "START_ATTACK_SUCCESS",
  START_ATTACK_FAILED = "START_ATTACK_FAILED",
  START_SCANING = "START_SCANING",
  SCANING_SUCCESS = "SCANING_SUCCESS",
  SCANING_SUCCESS_ALL = "SCANING_SUCCESS_ALL",
  SCANING_FAILED = "SCANING_FAILED",
  TRANING = "TRANING",
  TRANING_SUCCESS = "TRANING_SUCCESS",
  TRANING_FAILED = "TRANING_FAILED",
  ADD_DETAIL_PROCESS = "ADD_DETAIL_PROCESS",
}
