export enum SocketEvents {
  // Emit from client event
  START_ATTACK = "START_ATTACK",

  // Emit from server event
  PREPARE_DATA = "PREPARE_DATA",
  PREPARE_DATA_FAILED = "PREPARE_DATA_FAILED",
  PREPARE_DATA_SUCCESS = "PREPARE_DATA_SUCCESS",
  SCANING = "SCANING",
  SCAN_FAILED = "SCAN_FAILED",
  SCAN_SUCCESS = "SCAN_SUCCESS",
  ATTACKING = "ATTACKING",
  ATTACK_FAILED = "ATTACK_FAILED",
  ATTACKING_SUCCESS = "ATTACKING_SUCCESS",
  GOT_SHELL = "GOT_SHELL",
  GOT_METERPRETER = "GOT_METERPRETER",
  ADD_DETAIL = "ADD_DETAIL",
  ATTACK_PATH = "ATTACK_PATH",
}
